"""`eventcontracts gen-windows` — emit a walk-forward window TOML.

Generates rolling `(train, validate, test)` triples between two dates and
writes them to a TOML file that `eventcontracts sweep --windows ...`
consumes. The defaults (14d train / 7d validate / 7d test, stepping by the
test length) are a sane starting point for daily-resolution research; tune
to your data and horizon.
"""

from __future__ import annotations

import argparse
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any


def register(subparsers: Any) -> None:
    parser = subparsers.add_parser(
        "gen-windows",
        help="Generate a rolling walk-forward windows TOML for `sweep`.",
    )
    parser.add_argument(
        "--start", type=str, required=True, help="ISO-8601 start of the period"
    )
    parser.add_argument(
        "--end", type=str, required=True, help="ISO-8601 end of the period"
    )
    parser.add_argument("--train-days", type=int, default=14)
    parser.add_argument("--validate-days", type=int, default=7)
    parser.add_argument("--test-days", type=int, default=7)
    parser.add_argument(
        "--step-days",
        type=int,
        default=None,
        help="Days to step between iterations (default: --test-days)",
    )
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument(
        "--prefix",
        type=str,
        default="wf",
        help="Prefix for generated window names (default: 'wf').",
    )
    parser.set_defaults(handler=_handle)


def _parse_iso(value: str) -> datetime:
    parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=UTC)
    return parsed.astimezone(UTC)


def _toml_window(name: str, kind: str, start: datetime, end: datetime) -> str:
    return (
        "[[windows]]\n"
        f'name = "{name}"\n'
        f'kind = "{kind}"\n'
        f'start = "{start.isoformat().replace("+00:00", "Z")}"\n'
        f'end = "{end.isoformat().replace("+00:00", "Z")}"\n'
    )


def _handle(args: argparse.Namespace) -> int:
    start = _parse_iso(args.start)
    end = _parse_iso(args.end)
    if end <= start:
        print(f"error: --end ({end}) must be after --start ({start})")
        return 2

    if args.train_days <= 0 or args.validate_days < 0 or args.test_days <= 0:
        print("error: --train-days and --test-days must be > 0, --validate-days >= 0")
        return 2

    step_days = args.step_days if args.step_days is not None else args.test_days
    if step_days <= 0:
        print("error: --step-days must be > 0")
        return 2

    span = timedelta(
        days=args.train_days + args.validate_days + args.test_days
    )
    step = timedelta(days=step_days)

    blocks: list[str] = [
        "# Auto-generated by `eventcontracts gen-windows`.\n",
        f"# Period: {start.isoformat()} .. {end.isoformat()}\n",
        (
            f"# Train: {args.train_days}d  Validate: {args.validate_days}d  "
            f"Test: {args.test_days}d  Step: {step_days}d\n\n"
        ),
    ]

    cursor = start
    iteration = 0
    while cursor + span <= end:
        train_start = cursor
        train_end = train_start + timedelta(days=args.train_days)
        validate_start = train_end
        validate_end = validate_start + timedelta(days=args.validate_days)
        test_start = validate_end
        test_end = test_start + timedelta(days=args.test_days)

        stamp = train_start.strftime("%Y%m%d")
        blocks.append(
            _toml_window(f"{args.prefix}_{stamp}_train", "train", train_start, train_end)
        )
        if args.validate_days > 0:
            blocks.append(
                _toml_window(
                    f"{args.prefix}_{stamp}_validate",
                    "validate",
                    validate_start,
                    validate_end,
                )
            )
        blocks.append(
            _toml_window(f"{args.prefix}_{stamp}_test", "test", test_start, test_end)
        )
        blocks.append("\n")
        cursor = cursor + step
        iteration += 1

    if iteration == 0:
        print(
            f"error: period {start}..{end} is shorter than train+validate+test "
            f"({span.days} days). Pick a longer period or smaller window sizes."
        )
        return 2

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(blocks), encoding="utf-8")
    print(f"gen-windows: wrote {iteration} walk-forward iteration(s) to {args.out}")
    return 0
